# Generated by Django 6.1 on 2026-09-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantations', '0002_plantation_nom_parcelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendement_estime', models.DecimalField(decimal_places=2, max_digits=8)),
                ('production_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recolte_estimee', models.DateField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('plantation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='plantations.plantation')),
            ],
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='simulation.resultat')),
            ],
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Faible', 'Faible'), ('Modéré', 'Modéré'), ('Élevé', 'Élevé')], max_length=10)),
                ('description', models.TextField()),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='simulation.resultat')),
            ],
        ),
    ]
