# Generated by Django 6.1 on 2026-09-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.DecimalField(decimal_places=2, help_text='Superficie en hectares', max_digits=8)),
                ('date_plantation', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='agriculture.culture')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='agriculture.departement')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='agriculture.region')),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantations', to='agriculture.sol')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
