# Generated by Django 6.1 on 2026-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='nom_parcelle',
            field=models.CharField(default='parcelle', max_length=100),
            preserve_default=False,
        ),
    ]
