# Generated by Django 6.1 on 2026-08-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sol', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ph_moyen', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='agriculture.region')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('cycle_jours', models.PositiveBigIntegerField(help_text='Durée du cycle de culture en jours')),
                ('pluviometrie_min', models.DecimalField(decimal_places=2, help_text='En mm', max_digits=6)),
                ('pluviometrie_max', models.DecimalField(decimal_places=2, help_text='En mm', max_digits=6)),
                ('temperature_min', models.DecimalField(decimal_places=1, help_text='En °C', max_digits=4)),
                ('temperature_max', models.DecimalField(decimal_places=1, help_text='En °C', max_digits=4)),
                ('rendement_moyen', models.DecimalField(decimal_places=2, help_text='En kg/hectare ou tonnes/hectare', max_digits=8)),
                ('sols_compatibles', models.ManyToManyField(related_name='cultures', to='agriculture.sol')),
            ],
        ),
    ]
