# Generated by Django 6.1 on 2026-09-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='rendement_moyen',
        ),
        migrations.AddField(
            model_name='culture',
            name='jour_semis_debut',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='culture',
            name='jour_semis_fin',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='culture',
            name='mois_semis_debut',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='mois_semis_fin',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='culture',
            name='plafond_date',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Pénalité maximale liée à la date de plantation.', max_digits=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='plafond_pluie',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Pénalité maximale liée à la pluviométrie.', max_digits=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='plafond_risque',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Pénalité maximale liée au risque climatique.', max_digits=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='plafond_sol',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Pénalité maximale liée au type de sol.', max_digits=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='plafond_temperature',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Pénalité maximale liée à la température.', max_digits=3),
        ),
        migrations.AddField(
            model_name='culture',
            name='rendement_reference',
            field=models.DecimalField(decimal_places=2, default=3.5, help_text='Rendement potentiel maximal en tonnes/hectare.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='culture',
            name='cycle_jours',
            field=models.PositiveIntegerField(help_text='Durée du cycle de culture en jours'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='pluviometrie_max',
            field=models.DecimalField(decimal_places=2, help_text='Pluviométrie maximale (mm)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='culture',
            name='pluviometrie_min',
            field=models.DecimalField(decimal_places=2, help_text='Pluviométrie minimale (mm)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='culture',
            name='temperature_max',
            field=models.DecimalField(decimal_places=1, help_text='Température maximale (°C)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='culture',
            name='temperature_min',
            field=models.DecimalField(decimal_places=1, help_text='Température minimale (°C)', max_digits=4),
        ),
    ]
